### ISSUE TITLE
RedisDocker keeps running after simulation is terminated 

### ISSUE THREAD

**Issue by kilianp14** [dos-group/vessim#121]
After the simulation ends or is terminated manually, the docker container for Redis does not stop. This is very likely due to the incompatibility of the python multiprocessing and atexit libraries.

**Comment by marvin-steinke** [comment]
Before #112 this was working fine though, even with multiprocessing.

**Comment by marvin-steinke** [comment]
> > Before #112 this was working fine though, even with multiprocessing.
> 
> Yes. It was working because everything was initialized in the main process and not the child process, what is the case now. There, the atexit functions were registered in the main process, which is entirely different and not problematic.

I see, that makes sense ;)

**Comment by marvin-steinke** [comment]
1. For the `ApiServer` we could implement signal handlers and cleanup functions etc. to somehow make this work. However this would make the base class very specific to the docker usecase which should be soley defined by the api_type object. We could also subclass the api server to implement this which would be rather unnecessary complex, though.

2. There's also this library called [multiexit](https://github.com/kuralabs/multiexit) which solves the problem atexit has with multiprocessing, extra dependency though.

3. We could just use a docker compose file and leave python out of it.

4. We can drop windows compatibilty. Fine by me, however some people (for some raisin) are using windows for work.
