### ISSUE TITLE
`Controller` will cause failed assertion if `Microgrid` did not initialize `p_delta` yet

### ISSUE THREAD

**Issue by Impelon** [dos-group/vessim#178]
If a controller is initialized with a `step_size` lower than its microgrid the controller will be stepped first.
This results in an assertion error here:
https://github.com/dos-group/vessim/blob/7f68bd814474ccea44c474c66ea48a403bd8012b/vessim/controller.py#L167

This is despite the `KeyError` explicitly being ignored earlier:

https://github.com/dos-group/vessim/blob/7f68bd814474ccea44c474c66ea48a403bd8012b/vessim/controller.py#L158-L161

Maybe setting `p_delta` to 0.0 in case it is not available yet (and removing the then unnecessary assertion) would be a suitable solution?
Or alternatively letting the Controller deal with a `None` value however it wants to.

**Comment by Impelon** [comment]
You are right, of course, that using the microgrid's `step_size` is sufficient in most cases (mine as well probably). I was first and foremost surprised about the `AssertionError` and the fact that the assertion was introduced because of the linter, not necessarily because the behaviour was wrong.

However, I did come up with a use-case for lower step-sizes on the controller, albeit perhaps not that common. If you wish to monitor the grid_signals with higher fidelity than the step-size of the microgrid.
_(This could be a realistic use-case if all actors in the grid are quite constant, so the microgrid is set to a step-size of e.g. 500.)_

Further, I gave the assertion one more thought and noticed it would trigger also if __all__ actors of the microgrid have a _higher_ `step_size` than the microgrid itsself.
<details><summary>Here is a minimal example:</summary>

```python
from vessim.cosim import Environment, Microgrid
from vessim.power_meter import MockPowerMeter
from vessim.controller import Controller
from vessim.actor import ComputingSystem

class DummyController(Controller):
    def start(self, microgrid, clock, grid_signals):
        pass
    def step(self, time, p_delta, actor_infos):
        print(time, p_delta, actor_infos)

env = Environment(sim_start=0)
pm=[MockPowerMeter(p=1.0)]
mg = Microgrid(actors=[ComputingSystem(step_size=100, power_meters=pm)], controllers=[DummyController()], step_size=30)
env.add_microgrid(mg)
env.run(100)
```
</details>

**Comment by birnbaum** [comment]
Thanks for the nice bug report and minimal example!

I changed the GridSim from being event-based to time-based and changed the initialization order to 1. actors, 2. grid, 3. controllers. That means that during simultaneous steps, the simulators will be processed in this order. Following, we will always have a valid p_delta from step 0 on.
