### ISSUE TITLE
Adjust API endpoints to paper

### ISSUE THREAD

**Issue by marvin-steinke** [dos-group/vessim#9]
The current API endpoints are not consistent with the endpoints defined in Philipps paper and need to be adjusted according to:

| Request Method | Endpoint         | Request Body                                                 | Description                                                                        |
|----------------|-----------------|--------------------------------------------------------------|------------------------------------------------------------------------------------|
| GET            | /solar           | -                                                            | Gets the current solar power production in W.                                      |
| GET            | /ci              | -                                                            | Gets the current grid carbon intensity in gCO2/kWh.                                |
| GET            | /battery-soc     | -                                                            | Gets the current battery state of charge in %.                                      |
| GET            | /forecasts/solar | -                                                            | Gets the solar forecast for the next 24 hours.                                     |
| GET            | /forecasts/ci    | -                                                            | Gets the grid carbon intensity for the next 24 hours.                              |
| PUT            | /ves/battery     | {"min_soc": 0.6, "grid_charge": 10}                          | Configures the battery: min_soc describes the minimum state of charge in %, and grid_charge the power at which the battery is charged from the public grid in W. |
| PUT            | /cs/nodes/{id}   | {"power_mode": "normal"}                                     | Configures the power mode of node {id} (see Table 2).                              |

Open Questions @birnbaum :
- What is the output format of the forecasts?

**Comment by birnbaum** [comment]
We're working on a new REST API and will not provide an implementation of the one from the journal paper
